nova0, nova1, nova2

diff --git a/bin/bin/nc-set b/bin/bin/nc-set
--- a/bin/bin/nc-set
+++ b/bin/bin/nc-set
@@ -2,21 +2,26 @@
 # nc-set - manage NC environment variable
 # This file needs to be sourced
 
-# if the input command is something like "another",
-# the resulting path will be ~/another/nova-commons
+# if the input command is something like "nova0",
+# the resulting path will be ~/nova0/nova-commons
 
 # Environment variable needed: NC_CACHE_FILE
 # Set in your .bash_profile
 
 ARG=$1
-NC_PATH=${HOME}/nova-commons
-if [ ! -z $ARG ]; then
-    NC_PATH=${HOME}/${ARG}/nova-commons
+if [ -z $ARG ]; then
+    echo "no arg!"
+    exit 1;
 fi
 
-export NC=${NC_PATH}
+NC_PATH=${HOME}/${ARG}/nova-commons
+if [ -f $NC_PATH ]; then
+    echo "Path not found: $NC_PATH"
+else
+    export NC=${NC_PATH}
+    echo $NC > $NC_CACHE_FILE
 
-echo $NC > ${NC_CACHE_FILE}
+    echo $NC
+    cd $NC
+fi
 
-echo $NC
-cd $NC
